# Generated by Django 3.1.1 on 2020-09-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Usuario',
        ),
    ]
